apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: yamitc-color-applicaitonset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - namespace: yamitc-dev
      - namespace: yamitc-test
      - namespace: yamitc-uat
  template:
    metadata:
      # will generate applications with different names for example (dev-color-app, test-color-app, etc..)
      name: '{{namespace}}-color-app'
    spec:
      # applications will be in default project for argocd
      project: default
      source:
        repoURL: git@github.com:amitopenwriteup/ArgoCD-ApplicationSet-Demo.git
        targetRevision: HEAD
        path: list-generator-example/deployment
      destination:
        # default cluster as destination, you can define multiple clusters in ArgoCD UI
        server: https://6C6D06137920FB7B2ADE9485E8FF6ABF.gr7.ap-south-1.eks.amazonaws.com
        # will deploy to different namespaces as different destinations 
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true


