apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-projects
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/amitopenwriteup/ArgoCD-ApplicationSet-Demo.git
          revision: HEAD
          directories:
          - path: git-dir-generator-example/argo-projects/*
      - list:
          elements:
          - namespace: dev
          - namespace: qa
          - namespace: prod
  template:
    metadata:
      name: '{{path.basename}}-{{namespace}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/amitopenwriteup/ArgoCD-ApplicationSet-Demo.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true

