apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-projects
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
      - git:
          repoURL: git@github.com:amitopenwriteup/ArgoCD-ApplicationSet-Demo.git
          revision: HEAD
          directories:
          - path: git-dir-generator-example/argo-projects/*
      - list:
          elements:
          - namespace: dev
          - namespace: qa
          - namespace: prod
  template:
    metadata:
      name: '{{path.basename}}-{{namespace}}'
    spec:
      project: stage-devseccops
      source:
        repoURL: git@github.com:amitopenwriteup/ArgoCD-ApplicationSet-Demo.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://6C6D06137920FB7B2ADE9485E8FF6ABF.gr7.ap-south-1.eks.amazonaws.com
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
